name: Stations  
on: [push]
jobs:
  deploy_source:
    name: Deploy API Using Lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true

      - name: /stations post lambda deploy zip
        uses: postman-open-technologies/stations@main
        with:
            args: zip -qq -r m-s-stations-po.zip stations/post/index.js node_modules
      - name: stations get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-stations-po
            zip_file: m-s-stations-po.zip
      - name: /stations get lambda deploy zip
        uses: postman-open-technologies/stations@main
        with:
            args: zip -qq -r m-s-stations-g.zip stations/get/index.js node_modules
      - name: stations get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-stations-g
            zip_file: m-s-stations-g.zip
      - name: /stations/{station_id} get lambda deploy zip
        uses: postman-open-technologies/stations@main
        with:
            args: zip -qq -r m-s-stations-station-g.zip stations/station_id/get/index.js node_modules
      - name: stations get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-stations-station-g
            zip_file: m-s-stations-station-g.zip
      - name: /stations/{station_id} put lambda deploy zip
        uses: postman-open-technologies/stations@main
        with:
            args: zip -qq -r m-s-stations-station-pu.zip stations/station_id/put/index.js node_modules
      - name: stations get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-stations-station-pu
            zip_file: m-s-stations-station-pu.zip
      - name: /stations/{station_id} delete lambda deploy zip
        uses: postman-open-technologies/stations@main
        with:
            args: zip -qq -r m-s-stations-station-d.zip stations/station_id/delete/index.js node_modules
      - name: stations get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-stations-station-d
            zip_file: m-s-stations-station-d.zip          